### PR TITLE
Clarify attribution of the Immediate64 implementation

### PR DESCRIPTION
**Pull request by craigfe**
CC @avsm.

### CODE REVIEW

**Comment by dinosaure** [comment]
Thanks

**Comment by hannesm** [comment]
I'm slightly confused: how can this package being advertised as being "MIT licensed" when parts of the source are "licensed along with the OCaml compiler system under LGPLv2"? I'm not a lawyer, but I'd appreciate one of the following:
(a) keep the license as MIT (and do not import "along with the OCaml compiler system under LGPLv2" code into this repository),
(b) keep the LICENSE.md file (and the opam file) reflect the code in this repository,
(c) ask the original author of the (LGPL) code in question whether a relicense to MIT in this package would be possible.

I understand other repositories in the mirage organisation (such as https://github.com/mirage/mirage-solo5/issues/66) have similar inconsistencies, but we should really clean that up.

**Comment by craigfe** [comment]
@jeremiedimino: with apologies for not having asked you this in advance, are you happy for [these 20 lines of code](https://github.com/mirage/optint/blob/master/src/optint.ml#L10-L31) to be re-licensed under MIT in this repository? 

If so, I'll adjust the comment accordingly; if not, I can revert [this commit](https://github.com/mirage/optint/commit/a784858449a3b11959e91f9e3c2216eddb5b650a).

**Comment by ghost** [comment]
Sure no problem :)

FTR, this code is also part of Base, which is already under MIT: https://github.com/janestreet/base/blob/221b085f3fcd77597f8245b4d73de3970b238e71/src/int63.ml#L9

**Comment by hannesm** [comment]
Thanks @CraigFe @jeremiedimino :)

**Pull request merged**
